######################################################################
##
## Filename: simple_multiplier_tb.udo
## Created on: Wed Mar 15 5:49:59 PM Iran Standard Time 2023
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
