######################################################################
##
## Filename: carry_save_multiplier_tb.udo
## Created on: Thu Mar 16 7:16:47 PM Iran Standard Time 2023
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
